#!/bin/bash

instructions() {
cat << EOF

Usage: etcdcontroll --prune <foldername>/<key_name>

options:
	--shell                get an interactive etcd shell
    --cluster-health       check the cluster health
    --start-container      start a etcd container (Example: --start-container [ listen ip ] )
    --prune string         delete all keys from etcd (example: --prune galera/my_wsrep_cluster)
    --list-keys string     List all keys (example: --prune galera/my_wsrep_cluster)

EOF
	exit 1;
}


# if [ "$#" -ne 1 ]; then

#   	instructions;

# fi

#echo "No host specified. Trying to detirmine the internal IP.";

IP="10.0.2.15";

#echo $IP;

if [ "$1" == "--prune" ];
then
    curl -sS http://$IP:2379/v2/keys/$2?recursive=true -XDELETE | python -m json.tool;
    exit 1;
fi

if [ "$1" == "--list-keys" ];
then
  curl -sS http://$IP:2379/v2/keys/$2?recursive=true | python -m json.tool;
  exit 1;
fi

if [ "$1" == "--cluster-health" ];
then
  echo "Working on it :)"
  curl -sS http://$IP:2379/v2/members?recursive=true | python -m json.tool;
  exit 1;
fi

if [ "$1" == '--start-container' ];
then
  echo ''
  echo 'Starting etcd';
  sudo docker run --net=host --name etcd quay.io/coreos/etcd:v3.1.3 \
    /usr/local/bin/etcd \
    --name infa0 \
    --data-dir=data.etcd --name infra0 \
    --initial-advertise-peer-urls http://$2:2380 --listen-peer-urls http://$2:2380 \
    --advertise-client-urls http://$2:2379 --listen-client-urls http://$2:2379 \
    --initial-cluster infra0=http://$2:2380 \
    --initial-cluster-state new --initial-cluster-token etcdtoken &
  sleep 5;
  echo 'Success';
  exit 1;
fi

instructions;