#!/bin/bash

if [ "$#" -ne 2 ]; then

  cat << EOF

        Usage: script.sh --prune <foldername>/<key_name>

        options:
                --prune string          delete all keys from etcd " (example: --prune galera/my_wsrep_cluster)"
                --list-keys string      List all keys "(example: --prune galera/my_wsrep_cluster)"

EOF
exit 1;
fi

#echo "No host specified. Trying to detirmine the internal IP.";

IP="10.0.2.15";

#echo $IP;

if [ "$1" == "--prune" ];
then
        curl -sS http://$IP:2379/v2/keys/$2?recursive=true -XDELETE;
        exit 1;
fi

if [ "$1" == "--list-keys" ];
then
  curl -sS http://$IP:2379/v2/keys/$2?recursive=true | python -m json.tool;
  exit 1;
fi
