#!/bin/bash

instructions() {
cat << EOF

Usage: etcdcontroll --prune <foldername>/<key_name>

options:
	--shell                get an interactive etcd shell
    --cluster-health [ etcd ip ]      check the cluster health 
    --start-container [ etcd ip ]     start a etcd container (Example: --start-container [ listen ip ] )
    --prune string [ etcd ip ]        delete all keys from etcd (example: --prune galera/my_wsrep_cluster [ etcd ip ] )
    --list-keys string [ etcd ip ]    List all keys (example: --prune galera/my_wsrep_cluster [ etcd ip ])

EOF
	exit 1;
}

prune() {
  curl -sS http://$3:2379/v2/keys/$2?recursive=true -XDELETE | python -m json.tool;
  exit;
}

list_keys() {
  curl -sS http://$3:2379/v2/keys/$2?recursive=true | python -m json.tool;
  exit;
}

cluster_health() {
  curl -sS http://$2:2379/v2/members?recursive=true | python -m json.tool;
  exit;
}

if [ -z "$3" ];
then
  echo "You did not specify an IP address"
  exit;
fi

IP=$2;

if [ "$1" == "--prune" ];
then
  prune;
fi

if [ "$1" == "--list-keys" ];
then
  list_keys;
fi

if [ "$1" == "--cluster-health" ];
then
  echo "Working on it :)"
  cluster_health;
fi




if [ "$1" == '--start-container' ];
then
  echo ''
  echo 'Starting etcd';
  sudo docker run --net=host --name etcd quay.io/coreos/etcd:v3.1.3 \
    /usr/local/bin/etcd \
    --name infa0 \
    --data-dir=data.etcd --name infra0 \
    --initial-advertise-peer-urls http://$2:2380 --listen-peer-urls http://$2:2380 \
    --advertise-client-urls http://$2:2379 --listen-client-urls http://$2:2379 \
    --initial-cluster infra0=http://$2:2380 \
    --initial-cluster-state new --initial-cluster-token etcdtoken &
  sleep 5;
  echo 'Success';
  exit 1;
fi

instructions;