#!/bin/bash

start_etcd() {
  echo ''
  echo 'Starting etcd';
  sudo docker run --net=host --name etcd quay.io/coreos/etcd:v3.1.3 \
    /usr/local/bin/etcd \
    --name infa0 \
    --data-dir=data.etcd --name infra0 \
    --initial-advertise-peer-urls http://$etcdnetwork:2380 --listen-peer-urls http://$etcdnetwork:2380 \
    --advertise-client-urls http://$etcdnetwork:2379 --listen-client-urls http://$etcdnetwork:2379 \
    --initial-cluster infra0=http://$etcdnetwork:2380 \
    --initial-cluster-state new --initial-cluster-token etcdtoken &
}

detect_etcd() {
  curl -sS http://$etcdnetwork:2379/version 
  echo 'etcd detected';
}

testing(){
  echo 'success';
}

start_xtradb_cluster() {
  docker service create \
    --name client-mysql-master$n \
    --network $network \
    --mount type=volume,source=galeradb$n,target=/var/lib/mysql \
    -e MYSQL_ROOT_PASSWORD=$mysqlroot \
    -e DISCOVERY_SERVICE=$etcdnetwork:2379 \
    -e XTRABACKUP_PASSWORD=$mysqlroot \
    -e CLUSTER_NAME=$clustername \
    severalnines/pxc56
}

choose_network() {
  echo 'What network would you like to use?';
  echo '';
  docker network ls
  echo '';
  echo -n 'Choose one (name): ';
  read network
}

create_network() {
  echo -n 'Please specify a network name: ';
  read network;

  docker network create \
    --driver overlay \
    $network
}

get_images() {
  docker pull severalnines/pxc56;
  docker pull quay.io/coreos/etcd:v3.1.3
}

instructions() {
    echo 'Deploy and controll a high available PerconaXtraDB cluster'
    echo 'Note: not production ready. Use at own risk'
    echo ''
    echo 'options:';
    echo '    -n | --new-cluster    New cluster'
    echo '    -s | --scale          Scale the cluster'
    echo '    -h | --help           Show instructions'   
}