#!/bin/bash

. /opt/docker-scripts/perconaxtradb/functions
. /opt/docker-scripts/perconaxtradb/deploy
. /opt/docker-scripts/perconaxtradb/scale

while [ ! $# -eq 0 ]
do
  case "$1" in
    --scale | -s)
      echo 'scale'
      exit
      ;;
    --new-cluster | -n)
      deploy
      exit
      ;;
    --help | -h)
      instructions
      exit
      ;;
    *)
      instructions
      exit
      ;;
  esac
  shift
done

if [ -n "$2" ] || [ -n "s1" ];
then 
  instructions
exit;
fi